site_name: PaaSXpert Usage 
theme:
  name: material
  palette:
    primary: blue  
  icon:
    logo: material/cloud
  favicon: images/favicon.ico
  custom_dir: overrides
  language: kr
nav:
  - 'index.md'
  - '사용자 가이드':
    - 'user-guide/developer.md'
    - 'user-guide/deployer.md'
    - 'user-guide/manager.md'
    - 'user-guide/admin.md'
  - '운영자 가이드': 'admin-guide.md'
copyright: Copyright &copy; 2016 CROSSENT
extra:
  generator: false  
